baseURL = "/hugo-seven/" # "https://hugoseven.netlify.app"
languageCode = "th"
title = "Attajak Janrak"
description = "ชื่อคิง เกิด ๘ สิงหาฯ เลือดกรุ๊ปเอ"
theme = []

hasCJKLanguage = false
# defaultContentLanguage = "th"

[pagination]
  pagerSize = 18

enableGitInfo = true
enableEmoji = true
      
[mediaTypes.'application/x-ndjson']
  suffixes = ["ndjson"]

[outputs]
  home = ["HTML", "rss", "Algolia"]

[outputFormats]
  [outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    notAlternative = true
    mediaType = "application/x-ndjson"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = false

  [markup.tableOfContents]
    endLevel = 3
    startLevel = 2

[build]
  noJSConfigInAssets = false
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

[services]
  [services.disqus]
    shortname = "" # "seven-demo"  

[sitemap]
  filename = 'sitemap.xml'
  priority = -1

[taxonomies]
  category = 'categories'
  tag = 'tags'
